spring:
  datasource:
    url: jdbc:mysql://bj-cdb-mmv0qh5t.sql.tencentcdb.com:63664/voice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 134679852lyy
  jpa:
    hibernate:
      ddl-auto: update
wechat:
  appid: wx71aafc68f6c46172
  secret: b1c36aeec83b253e988b3112cad06650