spring:
  datasource:
    url: jdbc:mysql://139.199.130.100:3306/voice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 134679852lyy
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
  mvc:
    static-path-pattern: /static/**
wechat:
  appId: wx71aafc68f6c46172
  secret: b1c36aeec83b253e988b3112cad06650
  imagePath: D:\workspace\wechat-voice\resources\imageUpload
#  imagepath: /root/images